// file: plugins/tools/shortlink.js
import fetch from "node-fetch";

const shortlinkHandler = async (m, { sock, text }) => {
    // 1. Validasi input URL
    if (!text) {
        return await sock.sendMessage(m.key.remoteJid, { 
            text: `❗ Masukkan URL yang ingin diperpendek.\nContoh: ${global.prefix}shorten https://youtube.com/shorts/xxxx` 
        }, { quoted: m });
    }

    // Pastikan input adalah URL yang valid
    const urlRegex = /https?:\/\/[^\s$.?#].[^\s]*/g;
    const targetUrl = text.match(urlRegex);

    if (!targetUrl) {
        return await sock.sendMessage(m.key.remoteJid, { text: "❌ URL tidak valid. Pastikan menyertakan http:// atau https://" }, { quoted: m });
    }

    try {
        // 2. Panggil API TinyURL NekoLabs
        const apiUrl = `https://api.nekolabs.web.id/tools/shortlink/tinyurl?url=${encodeURIComponent(targetUrl[0])}`;
        const res = await fetch(apiUrl);
        const data = await res.json();

        if (data.success && data.result) {
            const caption = `🔗 *SHORTLINK GENERATED*\n\n` +
                            `*Original:* ${targetUrl[0]}\n` +
                            `*Short:* ${data.result}\n\n` +
                            `_Generated by ${global.botName}_`;

            await sock.sendMessage(m.key.remoteJid, { 
                text: caption,
                contextInfo: {
                    externalAdReply: {
                        title: "Shortlink Success",
                        body: data.result,
                        sourceUrl: data.result,
                        mediaType: 1,
                        renderLargerThumbnail: false
                    }
                }
            }, { quoted: m });
        } else {
            await sock.sendMessage(m.key.remoteJid, { text: "❌ Gagal memperpendek link. Silakan coba lagi." }, { quoted: m });
        }
    } catch (err) {
        console.error("[SHORTLINK ERROR]", err);
        await sock.sendMessage(m.key.remoteJid, { text: `❌ Terjadi kesalahan: ${err.message}` }, { quoted: m });
    }
};

// Pengaturan Command
shortlinkHandler.help = ['shorten', 'tinyurl'];
shortlinkHandler.tags = ['tools'];
shortlinkHandler.command = /^(shorten|tinyurl|shortlink)$/i;

export default shortlinkHandler;