import fetch from "node-fetch";

const waigenHandler = async (m, { sock, text, sender, consumeLimit }) => {
    // Pastikan prompt ada
    if (!text) {
        return await sock.sendMessage(m.key?.remoteJid || m.chat, {
            text: `❗ Masukkan prompt untuk generate gambar\nContoh: ${global.prefix}waigen Girl anime`
        }, { quoted: m.key ? m : undefined });
    }

    // Capture JID & quoted aman
    const jid = m.key?.remoteJid || m.chat;
    const quotedMsg = m.key ? m : undefined;

    // Kirim loading
    const loadingMsg = await sock.sendMessage(jid, { text: "⏳ Sedang generate gambar, harap tunggu..." }, { quoted: quotedMsg });

    try {
        const prompt = encodeURIComponent(text);
        const apiUrl = `https://api.nekolabs.web.id/image.gen/wai-anime-nsfw?prompt=${prompt}&ratio=9%3A16`;

        const res = await fetch(apiUrl, { timeout: 60000 });
        const json = await res.json();

        if (!json.success || !json.result) {
            return await sock.sendMessage(jid, { text: "❌ Gagal generate gambar. Silakan coba lagi nanti." }, { quoted: quotedMsg });
        }

        const caption = `*「 AI ANIME GENERATOR 」*\n\n` +
                        `◦ *Prompt:* ${text}\n` +
                        `◦ *Ratio:* 9:16\n` +
                        `◦ *Model:* Wai Anime (NSFW)\n\n` +
                        `_Generated by ${global.botName}_`;

        // Kirim gambar hasil generate
        await sock.sendMessage(jid, { 
            image: { url: json.result },
            caption
        }, { quoted: quotedMsg });

        // Hanya kurangi limit jika berhasil
        if (consumeLimit) consumeLimit(sender, 1);

        // Hapus pesan loading
        await sock.sendMessage(jid, { delete: loadingMsg.key });

    } catch (err) {
        console.error("[WAIGEN ERROR]", err);
        await sock.sendMessage(jid, { text: "❌ Terjadi kesalahan saat generate gambar." }, { quoted: quotedMsg });
    }
};

waigenHandler.help = ['waigen', 'animegen'];
waigenHandler.tags = ['premium'];
waigenHandler.command = /^(waigen|animegen)$/i;
waigenHandler.limit = 5; 
waigenHandler.cooldown = 10000; 
waigenHandler.premium = true; 

export default waigenHandler;