// file: plugins/ai/dalle2.js
import fetch from "node-fetch";

const dalle2Handler = async (m, { sock, text, sender, consumeLimit }) => {
    // 1. Validasi input prompt
    if (!text) {
        return await sock.sendMessage(m.key?.remoteJid || m.chat, {
            text: `❗ Masukkan prompt untuk DALL-E 2\nContoh: ${global.prefix}dalle2 1girl, cyberpunk, digital art`
        }, { quoted: m });
    }

    const jid = m.key?.remoteJid || m.chat;

    // 2. Kirim pesan loading
    const { key: loadingKey } = await sock.sendMessage(jid, { 
        text: "⏳ Sedang memproses gambar dengan OpenAI DALL-E 2...\nEstimasi waktu: 60-90 detik." 
    }, { quoted: m });

    try {
        const prompt = encodeURIComponent(text);
        // Menggunakan endpoint dall-e/2 dengan ratio 9:16 (sesuai curl Anda)
        const apiUrl = `https://api.nekolabs.web.id/image.gen/dall-e/2?prompt=${prompt}&ratio=9%3A16`;

        // Timeout 2 menit karena response time ±64 detik
        const res = await fetch(apiUrl, { timeout: 120000 });
        const json = await res.json();

        if (!json.success || !json.result) {
            await sock.sendMessage(jid, { text: "❌ Gagal generate gambar dengan DALL-E 2." }, { quoted: m });
            return await sock.sendMessage(jid, { delete: loadingKey });
        }

        const caption = `*「 DALL-E 2 GENERATOR 」*\n\n` +
                        `◦ *Prompt:* ${text}\n` +
                        `◦ *Ratio:* 9:16 (Portrait)\n` +
                        `◦ *Model:* OpenAI DALL-E v2\n\n` +
                        `_Generated by ${global.botName}_`;

        // 3. Kirim hasil gambar
        await sock.sendMessage(jid, { 
            image: { url: json.result },
            caption
        }, { quoted: m });

        // Kurangi limit jika berhasil
        if (consumeLimit) consumeLimit(sender, 1);

        // Hapus pesan loading
        await sock.sendMessage(jid, { delete: loadingKey });

    } catch (err) {
        console.error("[DALLE2 ERROR]", err);
        await sock.sendMessage(jid, { text: "❌ Terjadi kesalahan teknis atau timeout." }, { quoted: m });
        await sock.sendMessage(jid, { delete: loadingKey });
    }
};

// Pengaturan Command
dalle2Handler.help = ['dalle2'];
dalle2Handler.tags = ['ai'];
dalle2Handler.command = /^(dalle2|dalle)$/i;

dalle2Handler.limit = 5; 
dalle2Handler.cooldown = 20000; 

export default dalle2Handler;