// file: plugins/ai/pixar.js
import fetch from "node-fetch";

const pixarHandler = async (m, { sock, text, sender, consumeLimit }) => {
    // 1. Validasi input prompt
    if (!text) {
        return await sock.sendMessage(m.key?.remoteJid || m.chat, {
            text: `❗ Masukkan prompt untuk Pixar Cartoon\nContoh: ${global.prefix}pixar cute cat in the hat, 3d style`
        }, { quoted: m });
    }

    const jid = m.key?.remoteJid || m.chat;

    // 2. Kirim pesan loading
    const { key: loadingKey } = await sock.sendMessage(jid, { 
        text: "⏳ Sedang memproses gambar gaya Pixar (3D)..." 
    }, { quoted: m });

    try {
        const prompt = encodeURIComponent(text);
        // Menggunakan endpoint pixar-cartoon dengan ratio 1:1
        const apiUrl = `https://api.nekolabs.web.id/image.gen/pixar-cartoon?prompt=${prompt}&ratio=1%3A1`;

        // Timeout 90 detik karena response time ±43 detik
        const res = await fetch(apiUrl, { timeout: 90000 });
        const json = await res.json();

        if (!json.success || !json.result) {
            await sock.sendMessage(jid, { text: "❌ Gagal generate gambar Pixar Cartoon." }, { quoted: m });
            return await sock.sendMessage(jid, { delete: loadingKey });
        }

        const caption = `*「 PIXAR CARTOON GENERATOR 」*\n\n` +
                        `◦ *Prompt:* ${text}\n` +
                        `◦ *Ratio:* 1:1 (Square)\n` +
                        `◦ *Model:* Pixar Cartoon 3D\n\n` +
                        `_Generated by ${global.botName}_`;

        // 3. Kirim hasil sebagai Gambar (otomatis render dari .webp ke image)
        await sock.sendMessage(jid, { 
            image: { url: json.result },
            caption
        }, { quoted: m });

        // Kurangi limit jika berhasil
        if (consumeLimit) consumeLimit(sender, 1);

        // Hapus pesan loading
        await sock.sendMessage(jid, { delete: loadingKey });

    } catch (err) {
        console.error("[PIXAR ERROR]", err);
        await sock.sendMessage(jid, { text: "❌ Terjadi kesalahan teknis atau timeout." }, { quoted: m });
        await sock.sendMessage(jid, { delete: loadingKey });
    }
};

// Pengaturan Command
pixarHandler.help = ['pixar', 'pixarcartoon'];
pixarHandler.tags = ['ai'];
pixarHandler.command = /^(pixar|pixarcartoon)$/i;

pixarHandler.limit = 5; 
pixarHandler.cooldown = 15000; 

export default pixarHandler;