// file: plugins/ai/qwen-image.js
import fetch from "node-fetch";

const qwenImageHandler = async (m, { sock, text, sender, consumeLimit }) => {
    // 1. Validasi input prompt
    if (!text) {
        return await sock.sendMessage(m.key?.remoteJid || m.chat, {
            text: `❗ Masukkan prompt untuk Qwen Image\nContoh: ${global.prefix}qwenimg 1girl, wearing kimono, cherry blossoms`
        }, { quoted: m });
    }

    const jid = m.key?.remoteJid || m.chat;

    // 2. Kirim pesan loading
    const { key: loadingKey } = await sock.sendMessage(jid, { 
        text: "⏳ Sedang memproses gambar dengan Qwen AI..." 
    }, { quoted: m });

    try {
        const prompt = encodeURIComponent(text);
        // Menggunakan endpoint qwen/image dengan ratio 1:1
        const apiUrl = `https://api.nekolabs.web.id/image.gen/qwen/image?prompt=${prompt}&ratio=1%3A1`;

        // Timeout 90 detik karena response time ±41 detik
        const res = await fetch(apiUrl, { timeout: 90000 });
        const json = await res.json();

        if (!json.success || !json.result) {
            await sock.sendMessage(jid, { text: "❌ Gagal generate gambar dengan Qwen Image." }, { quoted: m });
            return await sock.sendMessage(jid, { delete: loadingKey });
        }

        const caption = `*「 QWEN AI IMAGE GENERATOR 」*\n\n` +
                        `◦ *Prompt:* ${text}\n` +
                        `◦ *Ratio:* 1:1 (Square)\n` +
                        `◦ *Model:* Qwen Image\n\n` +
                        `_Generated by ${global.botName}_`;

        // 3. Kirim hasil sebagai Gambar
        await sock.sendMessage(jid, { 
            image: { url: json.result },
            caption
        }, { quoted: m });

        // Kurangi limit jika berhasil
        if (consumeLimit) consumeLimit(sender, 1);

        // Hapus pesan loading
        await sock.sendMessage(jid, { delete: loadingKey });

    } catch (err) {
        console.error("[QWEN-IMG ERROR]", err);
        await sock.sendMessage(jid, { text: "❌ Terjadi kesalahan teknis atau timeout pada Qwen API." }, { quoted: m });
        await sock.sendMessage(jid, { delete: loadingKey });
    }
};

// Pengaturan Command
qwenImageHandler.help = ['qwenimg', 'qwenimage'];
qwenImageHandler.tags = ['ai'];
qwenImageHandler.command = /^(qwenimg|qwenimage)$/i;

qwenImageHandler.limit = 5; 
qwenImageHandler.cooldown = 15000; 

export default qwenImageHandler;