import fetch from "node-fetch";

const waigen2Handler = async (m, { sock, text, sender, consumeLimit }) => {
    // Pastikan prompt ada
    if (!text) {
        return await sock.sendMessage(m.key?.remoteJid || m.chat, {
            text: `❗ Masukkan prompt untuk generate gambar\nContoh: ${global.prefix}waigen2 Girl anime`
        }, { quoted: m.key ? m : undefined });
    }

    const jid = m.key?.remoteJid || m.chat;
    const quotedMsg = m.key ? m : undefined;

    // Kirim loading
    const loadingMsg = await sock.sendMessage(jid, { 
        text: "⏳ Sedang generate gambar (Model: Illustrous v11 - Portrait)..." 
    }, { quoted: quotedMsg });

    try {
        const prompt = encodeURIComponent(text);
        // Ratio diubah menjadi 9:16 (9%3A16)
        const apiUrl = `https://api.nekolabs.web.id/image.gen/wai-nsfw-illustrous/v11?prompt=${prompt}&ratio=9%3A16`;

        const res = await fetch(apiUrl, { timeout: 90000 });
        const json = await res.json();

        if (!json.success || !json.result) {
            return await sock.sendMessage(jid, { text: "❌ Gagal generate gambar. Silakan coba lagi nanti." }, { quoted: quotedMsg });
        }

        const caption = `*「 AI ANIME GENERATOR V2 」*\n\n` +
                        `◦ *Prompt:* ${text}\n` +
                        `◦ *Ratio:* 9:16 (Portrait)\n` +
                        `◦ *Model:* Wai NSFW Illustrous v11\n\n` +
                        `_Generated by ${global.botName}_`;

        // Kirim gambar hasil generate
        await sock.sendMessage(jid, { 
            image: { url: json.result },
            caption
        }, { quoted: quotedMsg });

        // Hanya kurangi limit jika berhasil
        if (consumeLimit) consumeLimit(sender, 1);

        // Hapus pesan loading
        await sock.sendMessage(jid, { delete: loadingMsg.key });

    } catch (err) {
        console.error("[WAIGEN2 ERROR]", err);
        await sock.sendMessage(jid, { text: "❌ Terjadi kesalahan atau timeout saat generate gambar." }, { quoted: quotedMsg });
    }
};

// Command diubah menjadi waigen2 dan animegen2
waigen2Handler.help = ['waigen2', 'animegen2'];
waigen2Handler.tags = ['premium'];
waigen2Handler.command = /^(waigen2|animegen2)$/i;
waigen2Handler.limit = 5; 
waigen2Handler.cooldown = 15000; 
waigen2Handler.premium = true; 

export default waigen2Handler;