// file: plugins/ai/waigen3.js
import fetch from "node-fetch";

const waigen3Handler = async (m, { sock, text, sender, consumeLimit }) => {
    // Pastikan prompt ada
    if (!text) {
        return await sock.sendMessage(m.key?.remoteJid || m.chat, {
            text: `❗ Masukkan prompt untuk generate gambar V3\nContoh: ${global.prefix}waigen3 Girl anime, blue hair`
        }, { quoted: m.key ? m : undefined });
    }

    const jid = m.key?.remoteJid || m.chat;
    const quotedMsg = m.key ? m : undefined;

    // Kirim loading dengan informasi model V3 (v12)
    const { key: loadingKey } = await sock.sendMessage(jid, { 
        text: "⏳ Sedang generate gambar (Model: Illustrous V12 - V3 Edition)...\nEstimasi proses ±100 detik." 
    }, { quoted: quotedMsg });

    try {
        const prompt = encodeURIComponent(text);
        // Menggunakan endpoint v12 dengan ratio 9:16 (9%3A16)
        const apiUrl = `https://api.nekolabs.web.id/image.gen/wai-nsfw-illustrous/v12?prompt=${prompt}&ratio=9%3A16`;

        // Timeout diatur ke 120.000ms (2 menit) karena respon time mencapai 98 detik
        const res = await fetch(apiUrl, { timeout: 120000 });
        const json = await res.json();

        if (!json.success || !json.result) {
            await sock.sendMessage(jid, { text: "❌ Gagal generate gambar V3. Silakan coba lagi nanti." }, { quoted: quotedMsg });
            return await sock.sendMessage(jid, { delete: loadingKey });
        }

        const caption = `*「 AI ANIME GENERATOR V3 」*\n\n` +
                        `◦ *Prompt:* ${text}\n` +
                        `◦ *Ratio:* 9:16 (Portrait)\n` +
                        `◦ *Model:* Wai NSFW Illustrous v12\n\n` +
                        `_Generated by ${global.botName}_`;

        // Kirim gambar hasil generate
        await sock.sendMessage(jid, { 
            image: { url: json.result },
            caption
        }, { quoted: quotedMsg });

        // Hanya kurangi limit jika berhasil
        if (consumeLimit) consumeLimit(sender, 1);

        // Hapus pesan loading
        await sock.sendMessage(jid, { delete: loadingKey });

    } catch (err) {
        console.error("[WAIGEN3 ERROR]", err);
        await sock.sendMessage(jid, { text: "❌ Terjadi kesalahan atau timeout (Proses terlalu lama)." }, { quoted: quotedMsg });
        await sock.sendMessage(jid, { delete: loadingKey });
    }
};

// Command untuk V3
waigen3Handler.help = ['waigen3', 'animegen3'];
waigen3Handler.tags = ['premium'];
waigen3Handler.command = /^(waigen3|animegen3)$/i;

// Mengingat prosesnya sangat berat (98 detik), sebaiknya cooldown dibuat lebih lama
waigen3Handler.limit = 10; 
waigen3Handler.cooldown = 30000; 
waigen3Handler.premium = true; 

export default waigen3Handler;