// file: plugins/ai/yayoimix.js
import fetch from "node-fetch";

const yayoiMixHandler = async (m, { sock, text, sender, consumeLimit }) => {
    // Pastikan prompt ada
    if (!text) {
        return await sock.sendMessage(m.key?.remoteJid || m.chat, {
            text: `❗ Masukkan prompt untuk YayoiMix\nContoh: ${global.prefix}yayoi Girl anime, cute, school uniform`
        }, { quoted: m });
    }

    const jid = m.key?.remoteJid || m.chat;

    // Kirim loading
    const { key: loadingKey } = await sock.sendMessage(jid, { 
        text: "⏳ Sedang memproses gambar dengan YayoiMix..." 
    }, { quoted: m });

    try {
        const prompt = encodeURIComponent(text);
        // Menggunakan endpoint yayoimix dengan ratio 1:1
        const apiUrl = `https://api.nekolabs.web.id/image.gen/yayoimix?prompt=${prompt}&ratio=1%3A1`;

        const res = await fetch(apiUrl, { timeout: 60000 });
        const json = await res.json();

        if (!json.success || !json.result) {
            await sock.sendMessage(jid, { text: "❌ Gagal generate gambar dengan YayoiMix." }, { quoted: m });
            return await sock.sendMessage(jid, { delete: loadingKey });
        }

        const caption = `*「 AI YAYOIMIX GENERATOR 」*\n\n` +
                        `◦ *Prompt:* ${text}\n` +
                        `◦ *Ratio:* 1:1 (Square)\n` +
                        `◦ *Model:* YayoiMix\n\n` +
                        `_Generated by ${global.botName}_`;

        // Kirim hasil sebagai gambar (meskipun source-nya webp, WA bisa render sebagai image)
        await sock.sendMessage(jid, { 
            image: { url: json.result },
            caption
        }, { quoted: m });

        // Kurangi limit jika berhasil
        if (consumeLimit) consumeLimit(sender, 1);

        // Hapus pesan loading
        await sock.sendMessage(jid, { delete: loadingKey });

    } catch (err) {
        console.error("[YAYOIMIX ERROR]", err);
        await sock.sendMessage(jid, { text: "❌ Terjadi kesalahan saat memproses YayoiMix." }, { quoted: m });
        await sock.sendMessage(jid, { delete: loadingKey });
    }
};

// Pengaturan Command
yayoiMixHandler.help = ['yayoi', 'yayoimix'];
yayoiMixHandler.tags = ['ai'];
yayoiMixHandler.command = /^(yayoi|yayoimix)$/i;

yayoiMixHandler.limit = 5; 
yayoiMixHandler.cooldown = 10000; 

export default yayoiMixHandler;