// file: plugins/ai/yiffymix.js
import fetch from "node-fetch";

const yiffyMixHandler = async (m, { sock, text, sender, consumeLimit }) => {
    // 1. Validasi input prompt
    if (!text) {
        return await sock.sendMessage(m.key?.remoteJid || m.chat, {
            text: `❗ Masukkan prompt untuk YiffyMix\nContoh: ${global.prefix}yiffymix 1girl, furry, cinematic, colorful`
        }, { quoted: m });
    }

    const jid = m.key?.remoteJid || m.chat;

    // 2. Kirim pesan loading
    const { key: loadingKey } = await sock.sendMessage(jid, { 
        text: "⏳ Sedang memproses gambar dengan YiffyMix (Portrait)..." 
    }, { quoted: m });

    try {
        const prompt = encodeURIComponent(text);
        // Menggunakan endpoint yiffymix dengan ratio 9:16
        const apiUrl = `https://api.nekolabs.web.id/image.gen/yiffymix?prompt=${prompt}&ratio=9%3A16`;

        // Timeout 90 detik karena response time ±37 detik
        const res = await fetch(apiUrl, { timeout: 90000 });
        const json = await res.json();

        if (!json.success || !json.result) {
            await sock.sendMessage(jid, { text: "❌ Gagal generate gambar dengan YiffyMix." }, { quoted: m });
            return await sock.sendMessage(jid, { delete: loadingKey });
        }

        const caption = `*「 AI YIFFYMIX GENERATOR 」*\n\n` +
                        `◦ *Prompt:* ${text}\n` +
                        `◦ *Ratio:* 9:16 (Portrait)\n` +
                        `◦ *Model:* YiffyMix\n\n` +
                        `_Generated by ${global.botName}_`;

        // 3. Kirim hasil sebagai Gambar
        await sock.sendMessage(jid, { 
            image: { url: json.result },
            caption
        }, { quoted: m });

        // Kurangi limit jika berhasil
        if (consumeLimit) consumeLimit(sender, 1);

        // Hapus pesan loading
        await sock.sendMessage(jid, { delete: loadingKey });

    } catch (err) {
        console.error("[YIFFYMIX ERROR]", err);
        await sock.sendMessage(jid, { text: "❌ Terjadi kesalahan teknis atau timeout." }, { quoted: m });
        await sock.sendMessage(jid, { delete: loadingKey });
    }
};

// Pengaturan Command
yiffyMixHandler.help = ['yiffymix', 'ymix'];
yiffyMixHandler.tags = ['ai', 'premium'];
yiffyMixHandler.command = /^(yiffymix|ymix)$/i;

yiffyMixHandler.limit = 5; 
yiffyMixHandler.cooldown = 15000; 
yiffyMixHandler.premium = true; 

export default yiffyMixHandler;